### ISSUE TITLE
Acme::Client::Error::Unauthorized: Error creating new cert

### ISSUE THREAD

**Issue by olliekav** [datamolecule/letsencrypt_http_challenge#2]
I've tried so many ways to get this working on Heroku yet it I always get the above error. The verification always fails as it says the /.well-known/acem-challenge/ is 'Not Found'. Am I missing something?

The `LE_HTTP_CHALLENGE_RESPONSE` exists on Heroku and I've restarted. It feels like the engine never mounts?

**Comment by olliekav** [comment]
From looking to this further and trying it manually it seems to be with the dot in the URL. So '.well-known' is not picked u by Rails.

**Comment by luclussier** [comment]
Can you post the full URL you access from your browser as well as the resulting log output please?
You should access example.com/.well-known/acme-challenge/_the_same_string_defined_by_LE_HTTP_CHALLENGE_RESPONSE_variable
